### ISSUE TITLE
when i alt-tab out of the game, the sound stops working

### ISSUE THREAD

**Issue by nickplj12** [Pre-Fortress-2/pf2#10]
title. yes, i have changed the sound mixer & reinstall it and the only way to fix it is to quit the game and rejoin the server i was in which is a major pain in the ass. i think it has something to do with my monitor audio but idkdkdkd

**Comment by nickplj12** [comment]
it works with snd_restart too but still annoying

**Comment by rawra89** [comment]
Closing issue. Engine issue can't be fixed.
