### ISSUE TITLE
DUSTBOWL - wacky collisions @ cut/restored flank

### ISSUE THREAD

**Issue by Cool-Username07** [Pre-Fortress-2/pf2#11]
The **truss001_256.mdl** at the cut flank **doesn't have collisions** since it's meant to be just outside of bounds, so **physics objects (grenades pipes etc) fall right through** because it's only covered with a playerclip. Potentially annoying to people fighting, I'd recommend just putting **a blockbullets over it** instead of recompiling the model (although it WOULD be useful for things outside of dustbowl).

**Video:**
https://github.com/Pre-Fortress-2/pf2/assets/100492148/ba79eb3b-cac7-43da-8b5e-10ae9589ec63

**Comment by justyn0** [comment]
Fixed in next update
