### ISSUE TITLE
error when opening the game

### ISSUE THREAD

**Issue by thegameraudi2023** [Pre-Fortress-2/pf2#15]
When i open it a window pops up with the title "Error!" it says "Can't Find Background image 'materials/console/background01_widescreen.vtf'" huh

**Comment by usernameunavalible0** [comment]
install Source SDK 2013 Multiplayer in the tools tab of your steam library

**Comment by thegameraudi2023** [comment]
[usernameunavalible0](https://github.com/usernameunavalible0) I put it in sourcemods and I already have it

**Comment by rawra89** [comment]
Reinstall the game. There is a file missing.

**Comment by thegameraudi2023** [comment]
rawra89 i already reinstalled it like 100 times
