### ISSUE TITLE
Linux - Game crashes when spectating someone and switching to first person

### ISSUE THREAD

**Issue by EeveeEuphoria** [Pre-Fortress-2/pf2#2]
OS: Arch Linux (EndeavourOS)
Kernel: 6.0.12-arch1-1
Command used to run game: prime-run %command% -steam -steam

Basically what the title says. When I die or if I'm using the spectator team, spectating a player and switching to their first-person perspective using spacebar/jump crashes the game. Unsure why this happens, hope it gets fixed!

**Comment by EeveeEuphoria** [comment]
This still happens on 0.7.1, just to let you know.

**Comment by dangreene0** [comment]
added this to 0.7.3 project. will test this soon.

**Comment by Tholp1** [comment]
[crash_20240709234026_3.dmp.core.zip](https://github.com/user-attachments/files/16155319/crash_20240709234026_3.dmp.core.zip)
I believe this is the same issue, dump from 0.7.3

**Comment by dangreene0** [comment]
We believe this is fixed and will be implemented in 0.7.4
