### ISSUE TITLE
Game wont open on steam library

### ISSUE THREAD

**Issue by Toastedsodas** [Pre-Fortress-2/pf2#22]
Everytime i open it, it just wont load and still says the play button

**Comment by CobaltonGit** [comment]
You need Source SDK Base 2013 Multiplayer

**Comment by justyn0** [comment]
Stale issue. As the previous comment said, make sure that Source SDK Base 2013 Multiplayer is installed. For more information read the requirement section on the download page https://prefortress.com/download/#list.
