### ISSUE TITLE
Can't enable custom content

### ISSUE THREAD

**Issue by CobaltonGit** [Pre-Fortress-2/pf2#24]
I am trying to add a custom skin for a weapon to PF2, but the game still loads stock skin.
Is there any way to add it without messing in vpk files?

**Comment by justyn0** [comment]
This sounds like an issue with that mod itself or you may have installed the mod incorrectly. Make sure that you follow the mod's instructions correctly and that mod is made for PF2. Mods that is made for TF2 may not be compatible with PF2.
