### ISSUE TITLE
error during launch 

### ISSUE THREAD

**Issue by maxaul567** [Pre-Fortress-2/pf2#4]
hello tf player
![Capture d’écran (48)](https://user-images.githubusercontent.com/129291762/228537208-56bacf78-0c63-4a4d-9cbe-2ef0165353b8.png)
![Capture d’écran (49)](https://user-images.githubusercontent.com/129291762/228537218-0cf046e2-2be8-4568-a92a-6587f66c6c07.png)
 i installed the game and the sources 2013 i placed the patch 
and idk how to resolve this error i have to reinstall the .exe ?

**Comment by dangreene0** [comment]
make sure you:
- fully extract the pf2 files into the sourcemod folder
- have source sdk 2013 multiplayer installed
- source sdk 2013 is installed on the same drive as steam
- sourcemod folder is on the same drive as steam

**Comment by rawra89** [comment]
It's not an issue with the game, installation issue, closing
